name: Run experiments

on:
  push:
    branches:
      - "feat/experiments"

jobs:
  build:
    name: just do it
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run experiments
        run: |
          curl -I https://www.swisstopo.admin.ch/en/satellite-images-swisseo
      - name: Test curl with go client header
        run: docker run --rm alpine sh -c "apk add curl && curl -A \"Go-http-client/1.1\" https://www.swisstopo.admin.ch/en/satellite-images-swisseo -v"
