name: Build and publish container image

on:
  schedule:
    - cron: "42 1 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "feat/standalone-image-build"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "charts/oss-catalog/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Standalone build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create .env file
        run: |
          echo "PASETO_KEY=${{ secrets.PASETO_KEY }}" > .env
      - name: Start the backend api and database
        run: |
          docker compose up -d --build api
      - name: Wait for API to be ready
        run: |
          timeout 60 sh -c 'until docker compose ps api | grep -q "healthy"; do echo "Waiting for API..."; sleep 2; done'
          echo "API is ready!"
      - name: create paseto token
        run: |
          cd paseto/go
          PASETO_TOKEN="$(go run paseto-generate.go ${{ secrets.PASETO_KEY }})"
          echo "::add-mask::$PASETO_TOKEN"
          echo "PASETO_TOKEN=$PASETO_TOKEN" >> "$GITHUB_ENV"
      - name: Register Repositories from /swiss/index
        run: |
          echo "TODO: read/ parse repository list from /swiss/index/readme.md and send to api"
      - name: Run crawler
        run: |
          docker run --add-host=host.docker.internal:host-gateway -e API_BEARER_TOKEN=${{ env.PASETO_TOKEN }} -e API_BASEURL=http://host.docker.internal:3000/v1 -e GITHUB_TOKEN=${{ secrets.PAT_TOKEN_GITHUB }} italia/publiccode-crawler:latest
      - name: Build client with npm
        run: |
          cd client
          npm ci
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/dist

  # build_and_publish_image:
  #   name: Push container image to ghcr
  #   runs-on: ubuntu-latest
  #   needs: [update_db]

  #   permissions:
  #     contents: read
  #     packages: write
  #     attestations: write
  #     id-token: write

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v3.4.0
  #       with:
  #         registry: ${{ env.REGISTRY }}
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Extract metadata (tags, labels) for Docker
  #       id: meta
  #       uses: docker/metadata-action@v5.7.0
  #       with:
  #         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  #     - name: Build and push Docker image
  #       id: push
  #       uses: docker/build-push-action@v6.17.0
  #       with:
  #         context: .
  #         build-args: |
  #           API_BASEURL=${{ vars.API_URL }}
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}

  #     - name: Generate artifact attestation
  #       uses: actions/attest-build-provenance@v2
  #       with:
  #         subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
  #         subject-digest: ${{ steps.push.outputs.digest }}
  #         push-to-registry: true
